### ISSUE TITLE
Inference code

### ISSUE THREAD

**Issue by MMNavetty** [realcrane/Human-Trajectory-Prediction-via-Neural-Social-Physics#2]
Hello,
I'm very interested in your work, knowing you beat state of the art in the main trajectory forecasting dataset. I'm currentrly training some custom model for my application.
Is there an inference code to use your model ? I think i can make my own using "test" function but if you already have one can you push it to the git ? thanks
Keep up with the great research work !
MM

**Comment by JiangbeiYue** [comment]
Hi,

Maybe you can load trained models, skip training and use the test function directly to infer.
