### ISSUE TITLE
ETH dataset

### ISSUE THREAD

**Issue by sonorousduck** [realcrane/Human-Trajectory-Prediction-via-Neural-Social-Physics#3]
I noticed that your network performed the best on the ETH dataset and had a few questions on this as we are wanting to adapt it to a different research topic. The saved weights for SDD were available and I am assuming that the model can train to work on ETH as well. For the dataset, did you need the annotations? Along with do you have code for loading in the dataset/training on it?

**Comment by JiangbeiYue** [comment]
Hi, thanks for your focus. You can use the code under /data/SDD_ini/ to process the ETH dataset. Training on the ETH dataset is the same as training on SDD.

**Comment by sonorousduck** [comment]
Thank you!
